import {configureStore} from "@reduxjs/toolkit";
import {apiSlice} from "@/store/api/apiSlice";
import authReducer from "./feature/auth/AuthSlice"
import surveyReducer from "./feature/survey/surveySlide"
import voteReducer from "./feature/vote/voteSlice"
import fileuploadReducer from "./feature/fileupload/fileapislice"
import personalInfoReducer from './feature/personalInfo/personalInfoSlice';
import categoryReducer from './feature/category/categorySlide';
import questionReducer from './feature/question/questionSlide';
import responsesReducer from './feature/response/response'
import responsesVoteReducer from './feature/responsevote/response'
import submitSurveyReducer from './feature/response/surveySubmitResponse'
import displayReducer from './feature/config/displaySlice'
import submitVoteReducer from './feature/responsevote/voteSubmitResponse'

const store = configureStore({
    reducer: {
        [apiSlice.reducerPath]: apiSlice.reducer,
        // automatically generated by the api slice
        // reduc erPath is the name of the slice
        auth : authReducer,
        vote: voteReducer,
        survey: surveyReducer,
        category: categoryReducer,
        personalInfo: personalInfoReducer,
        fileupload: fileuploadReducer,
        question: questionReducer,
        responses: responsesReducer,
        responsesVote:responsesVoteReducer,
        submitSurvey: submitSurveyReducer,
        display: displayReducer,
        submitVote: submitVoteReducer,
    },
    // middleware: (getDefaultMiddleware) => {
    //     return getDefaultMiddleware().concat(apiSlice.middleware);
    //     // automatically generated by the api slice
    //     // middleware is the middleware that we need to add to our store
    //     // this need for rtks query to work with cache and other stuff
    // },
    middleware: (getDefaultMiddleware) => {
        return getDefaultMiddleware().concat(apiSlice.middleware);
    },
    devTools: true,
});

export default store;