ARG $ARG_PORT=8081

FROM gradle:7.5.1-jdk17 AS builder
WORKDIR /app
COPY --chown=gradle:gradle api/ .
RUN gradle build --no-daemon

FROM ibm-semeru-runtimes:open-17.0.14_7-jre AS runtime
WORKDIR /app
VOLUME /tmp/files
# RUN apk update && apk add -yq fontconfig ttf-dejavu
# RUN apt-get update && ap-get install -y fontconfig ttf-dejavu
COPY --from=builder /app/build/libs/*.jar /app/app.jar
EXPOSE ${ARG_PORT}
